### ISSUE TITLE
Issue with modules.

### ISSUE THREAD

**Issue by nordic16** [acxz/element-wal#1]
Hi. I followed the installation instructions, but it still doesn't work.
I made sure to double-check if `jq` was installed, which it was.

Stack trace: 
```
/home/nordic7/.config/Element exists: yes
/home/nordic7/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /usr/lib/element/app.asar/lib/language-helper.js
- /usr/lib/element/app.asar/lib/tray.js
- /usr/lib/element/app.asar/lib/electron-main.js
- /usr/lib/electron15/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at AppLocalization.fetchTranslationJson (/usr/lib/element/app.asar/lib/language-helper.js:76:20)
    at /usr/lib/element/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/lib/element/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/element/app.asar/lib/language-helper.js',
    '/usr/lib/element/app.asar/lib/tray.js',
    '/usr/lib/element/app.asar/lib/electron-main.js',
    '/usr/lib/electron15/resources/default_app.asar/main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
[5154:0206/132603.496098:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /usr/lib/element/app.asar/lib/language-helper.js
- /usr/lib/element/app.asar/lib/tray.js
- /usr/lib/element/app.asar/lib/electron-main.js
- /usr/lib/electron15/resources/default_app.asar/main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at AppLocalization.fetchTranslationJson (/usr/lib/element/app.asar/lib/language-helper.js:76:20)
    at /usr/lib/element/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/lib/element/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/element/app.asar/lib/language-helper.js',
    '/usr/lib/element/app.asar/lib/tray.js',
    '/usr/lib/element/app.asar/lib/electron-main.js',
    '/usr/lib/electron15/resources/default_app.asar/main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

I believe this error has to do with this script not being able to find the `en` module.

**Comment by acxz** [comment]
Is `element-desktop` still able to open up? The above issue you posted shouldn't cause element to break. I believe this is the upstream issue: https://github.com/vector-im/element-desktop/issues/871

Can you post your `~/.config/Element/config.json`?
As well as posting the output of `genelementconfig`?

**Comment by nordic16** [comment]
Yes, it still opens element.
I'm using the [default](https://develop.element.io/config.json) config. 

As for the output of `genelementconfig`:
`jq: error (at <stdin>:48): Cannot iterate over null (null)`

I ran `mv config.json config_old.json` before runing `genelementconfig` though.

**Comment by acxz** [comment]
I see maybe my script requires there to be a config file already existing. Let me test locally and push out a fix.

**Comment by acxz** [comment]
@nordic16 go ahead and check to see if the latest head works for you (5990d1b)

The script should now handle cases where `config.json` does not exist and has to be created.
I also redirected the warning u saw to /dev/null.

**Comment by nordic16** [comment]
@acxz Thanks! It works like a charm!
